# Generated by Django 2.0 on 2017-12-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='birthday',
            field=models.DateTimeField(blank=True),
        ),
    ]
