# Generated by Django 2.0 on 2017-12-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171208_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sns',
            name='account_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='sns',
            name='name',
            field=models.CharField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
