# Generated by Django 2.0 on 2018-01-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sns',
            name='account_name',
        ),
    ]
